module.exports={
    BASE_URL:'http://localhost:3000/',
    MOVIE:'Movie',
    USERS:'/users/insert',
    LOGIN:'user',
    CITY:'city/getAll',
    THEATRE:'theatre/getOne',
    LOGOUT:'users/deleteToken',
    MOVIERELEASED:'theatreMovie/getOne/',
    GETSCREEN:'screen/getOne/'
};